#!/bin/sh

number=10001
aleatorio=$(((RANDOM%1000)+1))
echo "Try to guess the number I thought!"
until [[ $number = $aleatorio ]]; do
	echo -n "Choose a number (1 to 1000):  "
	read number
	if [[ $number > $aleatorio ]]; then
		echo "My number is lower than $number"
	elif [[ $number < $aleatorio ]]; then
		echo "My number is higher than $number"
	fi
done

echo "Congratulations, you guessed correctly"
