#!/bin/sh

read -p "Primeiro número: " n1
read -p "Segundo número: " n2
read -p "Terceiro número: " n3

if [ $n1 -gt $n2 ] && [ $n1 -gt $n3 ]; then
   maior=$n1
elif [ $n2 -gt $n1 ] && [ $n2 -gt $n3 ]; then
   maior=$n2
else
   maior=$n3
fi

echo "O maior número é o $maior"
